In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv('day6_data1.csv')
data

alcohol  sugar    pH  class
0         9.4    1.9  3.51    0.0
1         9.8    2.6  3.20    0.0
2         9.8    2.3  3.26    0.0
3         9.8    1.9  3.16    0.0
4         9.4    1.9  3.51    0.0
...       ...    ...   ...    ...
6492     11.2    1.6  3.27    1.0
6493      9.6    8.0  3.15    1.0
6494      9.4    1.2  2.99    1.0
6495     12.8    1.1  3.34    1.0
6496     11.8    0.8  3.26    1.0

[6497 rows x 4 columns]

In [2]:
X = data[['alcohol', 'sugar', 'pH']].to_numpy()
Y = data['class'].to_numpy()

from sklearn.model_selection import train_test_split
t_x, tt_x, t_y, tt_y = train_test_split(X, Y, random_state= 42, test_size= 0.2)

In [3]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state= 42)
sc = cross_validate(rf, t_x, t_y, return_train_score= True)
np.mean(sc['train_score']), np.mean(sc['test_score'])

(0.9973541965122431, 0.8905151032797809)

In [4]:
rf.fit(t_x, t_y)
rf.feature_importances_

array([0.23167441, 0.50039841, 0.26792718])

In [5]:
rf.score(t_x, t_y) , rf.score(tt_x, tt_y)

(0.996921300750433, 0.8892307692307693)

In [6]:
rf1 = RandomForestClassifier(oob_score= True, random_state= 42)
rf1.fit(t_x, t_y)

RandomForestClassifier(oob_score=True, random_state=42)

In [7]:
rf1.oob_score_

0.8934000384837406

In [8]:
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(random_state= 42)

sc = cross_validate(et, t_x, t_y, return_train_score= True)
np.mean(sc['train_score']), np.mean(sc['test_score'])

(0.9974503966084433, 0.8887848893166506)

In [9]:
et.fit(t_x, t_y)
rf.feature_importances_, et.feature_importances_

(array([0.23167441, 0.50039841, 0.26792718]),
 array([0.20183568, 0.52242907, 0.27573525]))

In [10]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(random_state= 42)

sc = cross_validate(gb, t_x, t_y, return_train_score= True)
np.mean(sc['train_score']), np.mean(sc['test_score'])

(0.8881086892152563, 0.8720430147331015)

In [11]:
gb = GradientBoostingClassifier(random_state= 42, n_estimators= 500, learning_rate= 0.2)

sc = cross_validate(gb, t_x, t_y, return_train_score= True)
np.mean(sc['train_score']), np.mean(sc['test_score'])

(0.9464595437171814, 0.8780082549788999)

In [12]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier

h = HistGradientBoostingClassifier(random_state= 42)

sc = cross_validate(h, t_x, t_y, return_train_score= True)
np.mean(sc['train_score']), np.mean(sc['test_score'])

(0.9321723946453317, 0.8801241948619236)