In [12]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt

data = pd.read_csv('data1_all.csv')
data_X = data[['Weight', 'Length', 'Diagonal', 'Height', 'Width']].to_numpy()
data_Y = data['Name'].to_numpy()

ss = StandardScaler().fit(data_X)
data_X = ss.transform(data_X)

t_x, tt_x, t_y, tt_y = train_test_split(data_X, data_Y, random_state= 42)

lr = LogisticRegression(C= 20, max_iter= 1000)  # 다중 분류
lr.fit(t_x, t_y)
print(lr.score(t_x, t_y), lr.score(tt_x, tt_y))

d = lr.decision_function(t_x[:1])

from scipy.special import softmax  # 다중 분류 소프트맥스 함수
print(np.round(softmax(d), ))

0.9243697478991597 0.925
[[1. 0. 0. 0. 0. 0. 0.]]


In [3]:
i = (t_y == 'A') | (t_y == 'G')
b_t_x = t_x[i]
b_t_y = t_y[i]

lr = LogisticRegression()
lr.fit(b_t_x, b_t_y)

LogisticRegression()

In [4]:
lr.coef_, lr.intercept_

(array([[-0.41981254, -0.60056128, -0.68786241, -1.00159093, -0.74532495]]),
 array([-2.1898649]))

In [8]:
d = lr.decision_function(b_t_x[:1])  # 학습된 공식을 꺼냄

In [9]:
from scipy.special import expit  # 단일 분류 시그모이드 함수

expit(d)

array([0.00254817])