In [2]:
# 소프트맥스 함수 구현

import numpy as np

def s_max(z):
    a_v = np.exp(z)
    return a_v / sum(a_v)

z = [2, 1, 5, 0.5]

y = s_max(z)
y

array([0.04613281, 0.01697131, 0.92660226, 0.01029362])

# minist 데이터셋 이용

In [4]:
from sklearn.datasets import load_digits

data = load_digits()
data.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [6]:
data['images'].shape

(1797, 8, 8)

In [7]:
data['target'][0]

0

In [9]:
data['images'][0]  # 이미지라서 가로 세로로 피쳐가 있음

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [11]:
data['data'][0].shape  # dataset에서 이미 전처리가 되어 있음

(64,)

# 데이터 분류

In [12]:
X = data['data']
Y = data['target']

from sklearn.model_selection import train_test_split

t_x, tt_x, t_y, tt_y = train_test_split(X, Y, random_state= 42)

# 모델 생성 및 학습

In [16]:
from sklearn.linear_model import LogisticRegression

lo_g_ovr = LogisticRegression(multi_class= 'ovr')
lo_g_s_max = LogisticRegression(multi_class= 'multinomial', solver= 'sag')

lo_g_ovr.fit(t_x, t_y)
lo_g_s_max.fit(t_x, t_y)

C:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_resu

LogisticRegression(multi_class='multinomial', solver='sag')

# 테스트 및 검증

In [17]:
from sklearn.metrics import confusion_matrix

y_t = tt_y.copy()
y_p = lo_g_ovr.predict(tt_x)

confusion_matrix(y_t, y_p)

array([[43,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 35,  1,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0, 38,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 44,  0,  1,  0,  0,  1,  0],
       [ 0,  1,  0,  0, 54,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0, 56,  0,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  1, 44,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 40,  0,  1],
       [ 0,  1,  0,  0,  0,  1,  0,  0, 36,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  4, 44]], dtype=int64)

In [18]:
from sklearn.metrics import classification_report

print(classification_report(y_t, y_p))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        43
           1       0.95      0.95      0.95        37
           2       0.95      1.00      0.97        38
           3       1.00      0.96      0.98        46
           4       1.00      0.98      0.99        55
           5       0.95      0.95      0.95        59
           6       1.00      0.98      0.99        45
           7       1.00      0.98      0.99        41
           8       0.84      0.95      0.89        38
           9       0.96      0.92      0.94        48

    accuracy                           0.96       450
   macro avg       0.96      0.97      0.96       450
weighted avg       0.97      0.96      0.96       450

